<table class="table table-striped-columns">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Color</th>
      <th scope="col">Deporte</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($productos as $producto) : ?>
      <tr>
        <th scope="row"> <?= $producto->id_producto ?> </th>
        <td> <a href="productoEspecifico/<?= $producto->id_producto ?>"><?= $producto->nombre ?></a></td>
        <td> <?= $producto->precio ?> </td>
        <td> <?= $producto->color ?> </td>
        <td> <?= $producto->id_deporte ?> </td>
      </tr>
    <?php endforeach ?>
  </tbody>
</table>