<div>
    <form action="auth" method="POST">
        <input type="text" name="username" class="form-control my-4 py-2" placeholder="Username" />
        <input type="password" name="password" class="form-control my-4 py-2" placeholder="Password" />
        <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary">Login</button>
        </div>
        <?php if ($error) : ?>
            <div class='alert alert-danger mt-3' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>
    </form>
</div>     
