<form action="agregarDeporte" method="POST" class="my-4">
    
        <div class="col-3">
            <div class="form-group">
                <label class="form-label" for="nombre">Nombre del deporte</label>
                <input class="form-control" type="text" name="deporte" id="deporte" placeholder="Ingresa el deporte">
            </div>
            <div class="mt-3">
                <button type="submit" class="btn btn-primary mt-2">Agregar Producto</button>
            </div>
        </div>
</form>

