<?php 
    if(isset($_SESSION['USER_NAME'])) :
    require_once 'templates/formDeportes.phtml';
    endif
?>

<table class="table table-striped-columns">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th>Nombre</th>
            <?php if(isset($_SESSION['USER_NAME'])) : ?>
            <th scope="col">Operaciones</th>
            <?php endif ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($deportes as $deporte): ?>
            <tr>
            <th scope="row"> <?= $deporte->id_deporte ?> </th>
                <td><?php echo $deporte->nombre; ?></td>
                <?php 
                if (isset($_SESSION['USER_NAME'])) :  ?>
                <td><a href="eliminarDeporte/<?= $deporte->id_deporte?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                    <a href="botonEditarDeporte/<?= $deporte->id_deporte?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                <?php endif
                ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


