<form action="agregarProducto" method="POST" class="my-4">
    <div class="row text-center">
        <div class="col-3">
            <div class="form-group">
                <label>Nombre</label>
                <input  name="nombre" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Precio</label>
                <input required name="precio" type="number" class="form-control">
            </div>

        </div><div class="col-3">
            <div class="form-group">
                <label>Color</label>
                <input required name="color" type="text" class="form-control">
            </div>
        </div>

        <div class="col-2">
            <div class="form-group">
                <label>Deportes</label>
                <select required name="id_deporte" class="form-control text-center">
                <?php foreach($deportes as $deporte): ?>
                    <option value="<?= $deporte->id_deporte ?>"> <?= $deporte->nombre ?> </option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>