
<table class="table table-striped-columns">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Color</th>
      <th scope="col">Deporte</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row"> <?= $itemPorID->id_producto ?> </th>
            <td> <?= $itemPorID->nombre ?> </td>
            <td> <?= $itemPorID->precio ?> </td>
            <td> <?= $itemPorID->color ?> </td>
            <td> <?= $itemPorID->id_deporte ?> </td>
         </tr>
  </tbody>
</table>